# Generated by Django 5.2.4 on 2025-08-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('confirmed', 'Подтвержден'), ('preparing', 'Готовится'), ('ready', 'Готов к выдаче'), ('delivered', 'Доставлен'), ('cancelled', 'Отменен')], default='pending', max_length=20),
        ),
    ]
