# Generated by Django 5.2.4 on 2025-07-28 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_alter_location_latitude_alter_location_longitude'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='position_on_map',
        ),
        migrations.AddField(
            model_name='shop',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='map.location'),
        ),
    ]
