# Generated by Django 5.2.4 on 2025-08-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_shop_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='opening_hours',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
